package com.na7q.hud

data class AprsPacket(
    val comment: String
) {
    companion object {
        // Existing COMMENT_DATA map
        private val COMMENT_DATA = mapOf(
            "_ " to mapOf("vendor" to "Yaesu", "model" to "VX-8", "class" to "ht"),
            "_\"" to mapOf("vendor" to "Yaesu", "model" to "FTM-350", "class" to "rig"),
            "_#" to mapOf("vendor" to "Yaesu", "model" to "VX-8G", "class" to "ht"),
            "_$" to mapOf("vendor" to "Yaesu", "model" to "FT1D", "class" to "ht"),
            "_(" to mapOf("vendor" to "Yaesu", "model" to "FT2D", "class" to "ht"),
            "_0" to mapOf("vendor" to "Yaesu", "model" to "FT3D", "class" to "ht"),
            "_3" to mapOf("vendor" to "Yaesu", "model" to "FT5D", "class" to "ht"),
            "_1" to mapOf("vendor" to "Yaesu", "model" to "FTM-300D", "class" to "rig"),
            "_)" to mapOf("vendor" to "Yaesu", "model" to "FTM-100D", "class" to "rig"),
            "_%" to mapOf("vendor" to "Yaesu", "model" to "FTM-400DR", "class" to "rig"),
            "_4" to mapOf("vendor" to "Yaesu", "model" to "FTM-500DR", "class" to "rig"),
            "[1" to mapOf("software" to "NA7Q", "model" to "APRSdroid", "class" to "rig"),
            "(5" to mapOf("vendor" to "Anytone", "model" to "D578UV", "class" to "ht"),
            "(8" to mapOf("vendor" to "Anytone", "model" to "D878UV", "class" to "ht"),
            "|3" to mapOf("vendor" to "Byonics", "model" to "TinyTrak3", "class" to "tracker"),
            "|4" to mapOf("vendor" to "Byonics", "model" to "TinyTrak4", "class" to "tracker"),
            "^v" to mapOf("vendor" to "HinzTec", "model" to "anyfrog"),
            "*v" to mapOf("vendor" to "KissOZ", "model" to "Tracker", "class" to "tracker")
        )

        // New TOCALL_DATA map
        private val TOCALL_DATA = mapOf(
			"BEACON" to mapOf("vendor" to "APRS", "model" to "Generic"),
			"ID" to mapOf("vendor" to "APRS", "model" to "Generic"),
			"AP1WWX" to mapOf("vendor" to "TAPR", "model" to "T-238+", "class" to "wx"),
			"AP4R??" to mapOf("vendor" to "Open Source", "model" to "APRS4R", "class" to "software"),
			"APAEP1" to mapOf("vendor" to "Paraguay Space Agency (AEP)", "model" to "EIRUAPRSDIGIS&FV1", "class" to "satellite"),
			"APAF??" to mapOf("model" to "AFilter"),
			"APAG??" to mapOf("model" to "AGate"),
			"APAGW" to mapOf("vendor" to "SV2AGW", "model" to "AGWtracker", "class" to "software", "os" to "Windows"),
			"APAGW?" to mapOf("vendor" to "SV2AGW", "model" to "AGWtracker", "class" to "software", "os" to "Windows"),
			"APAH??" to mapOf("model" to "AHub"),
			"APAM??" to mapOf("vendor" to "Altus Metrum", "model" to "AltOS", "class" to "tracker"),
			"APAND?" to mapOf("vendor" to "Open Source", "model" to "APRSdroid", "os" to "Android", "class" to "app"),
			"APAT51" to mapOf("vendor" to "Anytone", "model" to "AT-D578", "class" to "rig"),
			"APAT81" to mapOf("vendor" to "Anytone", "model" to "AT-D878", "class" to "ht"),
			"APAT??" to mapOf("vendor" to "Anytone"),
			"APATAR" to mapOf("vendor" to "TA7W/OH2UDS Baris Dinc and TA6AEU", "model" to "ATA-R APRS Digipeater", "class" to "digi"),
			"APAVT5" to mapOf("vendor" to "SainSonic", "model" to "AP510", "class" to "tracker"),
			"APAW??" to mapOf("vendor" to "SV2AGW", "model" to "AGWPE", "class" to "software", "os" to "Windows"),
			"APAX??" to mapOf("model" to "AFilterX"),
			"APB2MF" to mapOf("vendor" to "Mike, DL2MF", "model" to "MF2APRS Radiosonde tracking tool", "class" to "software", "os" to "Windows"),
			"APBK??" to mapOf("vendor" to "PY5BK", "model" to "Bravo Tracker", "class" to "tracker"),
			"APBL??" to mapOf("vendor" to "BigRedBee", "model" to "BeeLine GPS", "class" to "tracker"),
			"APBM??" to mapOf("vendor" to "R3ABM", "model" to "BrandMeister DMR"),
			"APBPQ??" to mapOf("vendor" to "John Wiseman, G8BPQ", "model" to "BPQ32", "class" to "software", "os" to "Windows"),
			"APBSD?" to mapOf("vendor" to "hambsd.org", "model" to "HamBSD"),
			"APBT62" to mapOf("vendor" to "BTech", "model" to "DMR 6x2"),
			"APC???" to mapOf("vendor" to "Rob Wittner, KZ5RW", "model" to "APRS/CE", "class" to "app"),
			"APCDS0" to mapOf("vendor" to "ZS6LMG", "model" to "cell tracker", "class" to "tracker"),
			"APCLEY" to mapOf("vendor" to "ZS6EY", "model" to "EYTraker", "class" to "tracker"),
			"APCLEZ" to mapOf("vendor" to "ZS6EY", "model" to "Telit EZ10 GSM application", "class" to "tracker"),
			"APCLUB" to mapOf("model" to "Brazil APRS network"),
			"APCLWX" to mapOf("vendor" to "ZS6EY", "model" to "EYWeather", "class" to "wx"),
			"APCN??" to mapOf("vendor" to "DG5OAW", "model" to "carNET"),
			"APCSMS" to mapOf("vendor" to "USNA", "model" to "Cosmos"),
			"APCSS" to mapOf("vendor" to "AMSAT", "model" to "CubeSatSim CubeSat Simulator"),
			"APCTLK" to mapOf("vendor" to "Open Source", "model" to "Codec2Talkie", "class" to "app"),
			"APCWP8" to mapOf("vendor" to "GM7HHB", "model" to "WinphoneAPRS", "class" to "app"),
			"APDF??" to mapOf("model" to "Automatic DF units"),
			"APDG??" to mapOf("vendor" to "Jonathan, G4KLX", "model" to "ircDDB Gateway", "class" to "dstar"),
			"APDI??" to mapOf("vendor" to "Bela, HA5DI", "model" to "DIXPRS", "class" to "software"),
			"APDNO?" to mapOf("vendor" to "DO3SWW", "model" to "APRSduino", "class" to "tracker", "os" to "embedded"),
			"APDPRS" to mapOf("vendor" to "unknown", "model" to "D-Star APDPRS", "class" to "dstar"),
			"APDR??" to mapOf("vendor" to "Open Source", "model" to "APRSdroid", "os" to "Android", "class" to "app"),
			"APDS??" to mapOf("vendor" to "SP9UOB", "model" to "dsDIGI", "os" to "embedded"),
			"APDST?" to mapOf("vendor" to "SP9UOB", "model" to "dsTracker", "os" to "embedded"),
			"APDT??" to mapOf("vendor" to "unknown", "model" to "APRStouch Tone (DTMF)"),
			"APDU??" to mapOf("vendor" to "JA7UDE", "model" to "U2APRS", "class" to "app", "os" to "Android"),
			"APDV??" to mapOf("vendor" to "OE6PLD", "model" to "SSTV with APRS", "class" to "software"),
			"APDW??" to mapOf("vendor" to "WB2OSZ", "model" to "DireWolf"),
			"APDnnn" to mapOf("vendor" to "Open Source", "model" to "aprsd", "class" to "software", "os" to "Linux/Unix"),
			"APE2A?" to mapOf("vendor" to "NoseyNick, VA3NNW", "model" to "Email-2-APRS gateway", "class" to "software", "os" to "Linux/Unix"),
			"APE???" to mapOf("model" to "Telemetry devices"),
			"APECAN" to mapOf("vendor" to "KT5TK/DL7AD", "model" to "Pecan Pico APRS Balloon Tracker", "class" to "tracker"),
			"APELK?" to mapOf("vendor" to "WB8ELK", "model" to "Balloon tracker", "class" to "tracker"),
			"APERS?" to mapOf("vendor" to "Jason, KG7YKZ", "model" to "Runner tracking", "class" to "tracker"),
			"APERXQ" to mapOf("vendor" to "PE1RXQ", "model" to "PE1RXQ APRS Tracker", "class" to "tracker"),
			"APESP?" to mapOf("vendor" to "LY3PH", "model" to "APRS-ESP", "os" to "embedded"),
			"APFG??" to mapOf("vendor" to "KP4DJT", "model" to "Flood Gage", "class" to "software"),
			"APFI??" to mapOf("vendor" to "aprs.fi", "class" to "app"),
			"APFII?" to mapOf("model" to "iPhone/iPad app", "vendor" to "aprs.fi", "os" to "ios", "class" to "app"),
			"APGBLN" to mapOf("vendor" to "NW5W", "model" to "GoBalloon", "class" to "tracker"),
			"APGO??" to mapOf("vendor" to "AA3NJ", "model" to "APRS-Go", "class" to "app"),
			"APHAX?" to mapOf("vendor" to "PY2UEP", "model" to "SM2APRS SondeMonitor", "class" to "software", "os" to "Windows"),
			"APHBL?" to mapOf("vendor" to "KF7EEL", "model" to "HBLink D-APRS Gateway", "class" to "software"),
			"APHH?" to mapOf("vendor" to "Steven D. Bragg, KA9MVA", "model" to "HamHud", "class" to "tracker"),
			"APHK??" to mapOf("vendor" to "LA1BR", "model" to "Digipeater/tracker"),
			"APHMEY" to mapOf("vendor" to "Tapio Heiskanen, OH2TH", "model" to "APRS-IS Client for Athom Homey", "contact" to "oh2th@iki.fi"),
			"APHPIA" to mapOf("vendor" to "HP3ICC", "model" to "Arduino APRS"),
			"APHPIB" to mapOf("vendor" to "HP3ICC", "model" to "Python APRS Beacon"),
			"APHPIW" to mapOf("vendor" to "HP3ICC", "model" to "Python APRS WX"),
			"APHT??" to mapOf("vendor" to "IU0AAC", "model" to "HMTracker", "class" to "tracker"),
			"APHW??" to mapOf("vendor" to "HamWAN"),
			"API282" to mapOf("vendor" to "Icom", "model" to "IC-2820", "class" to "dstar"),
			"API31" to mapOf("vendor" to "Icom", "model" to "IC-31", "class" to "dstar"),
			"API410" to mapOf("vendor" to "Icom", "model" to "IC-4100", "class" to "dstar"),
			"API51" to mapOf("vendor" to "Icom", "model" to "IC-51", "class" to "dstar"),
			"API510" to mapOf("vendor" to "Icom", "model" to "IC-5100", "class" to "dstar"),
			"API710" to mapOf("vendor" to "Icom", "model" to "IC-7100", "class" to "dstar"),
			"API80" to mapOf("vendor" to "Icom", "model" to "IC-80", "class" to "dstar"),
			"API880" to mapOf("vendor" to "Icom", "model" to "IC-880", "class" to "dstar"),
			"API910" to mapOf("vendor" to "Icom", "model" to "IC-9100", "class" to "dstar"),
			"API92" to mapOf("vendor" to "Icom", "model" to "IC-92", "class" to "dstar"),
			"API970" to mapOf("vendor" to "Icom", "model" to "IC-9700", "class" to "dstar"),
			"API???" to mapOf("vendor" to "Icom", "model" to "unknown", "class" to "dstar"),
			"APIC??" to mapOf("vendor" to "HA9MCQ", "model" to "PICiGATE"),
			"APIE??" to mapOf("vendor" to "W7KMV", "model" to "PiAPRS"),
			"APIN??" to mapOf("vendor" to "AB0WV", "model" to "PinPoint"),
			"APIZCI" to mapOf("vendor" to "TA7W/OH2UDS and TA6AEU", "model" to "hymTR IZCI Tracker", "class" to "tracker", "os" to "embedded"),
			"APJ8??" to mapOf("vendor" to "KN4CRD", "model" to "JS8Call", "class" to "software"),
			"APJA??" to mapOf("vendor" to "K4HG & AE5PL", "model" to "JavAPRS"),
			"APJE??" to mapOf("vendor" to "Gregg Wonderly, W5GGW", "model" to "JeAPRS"),
			"APJI??" to mapOf("vendor" to "Peter Loveall, AE5PL", "model" to "jAPRSIgate", "class" to "software"),
			"APJID2" to mapOf("vendor" to "Peter Loveall, AE5PL", "model" to "D-Star APJID2", "class" to "dstar"),
			"APJS??" to mapOf("vendor" to "Peter Loveall, AE5PL", "model" to "javAPRSSrvr"),
			"APJY??" to mapOf("vendor" to "KA2DDO", "model" to "YAAC", "class" to "software"),
			"APK003" to mapOf("vendor" to "Kenwood", "model" to "TH-D72", "class" to "ht"),
			"APK004" to mapOf("vendor" to "Kenwood", "model" to "TH-D74", "class" to "ht"),
			"APK005" to mapOf("vendor" to "Kenwood", "model" to "TH-D75", "class" to "ht"),
			"APK0??" to mapOf("vendor" to "Kenwood", "model" to "TH-D7", "class" to "ht"),
			"APK1??" to mapOf("vendor" to "Kenwood", "model" to "TM-D700", "class" to "rig"),
			"APKHTW" to mapOf("vendor" to "Kip, W3SN", "model" to "Tempest Weather Bridge", "class" to "wx", "os" to "embedded", "contact" to "w3sn@moxracing.33mail.com"),
			"APKRAM" to mapOf("vendor" to "kramstuff.com", "model" to "Ham Tracker", "class" to "app", "os" to "ios"),
			"APLC??" to mapOf("vendor" to "DL3DCW", "model" to "APRScube"),
			"APLDI?" to mapOf("vendor" to "David, OK2DDS", "model" to "LoRa IGate/Digipeater", "class" to "digi"),
			"APLDM?" to mapOf("vendor" to "David, OK2DDS", "model" to "LoRa Meteostation", "class" to "wx"),
			"APLETK" to mapOf("vendor" to "DL5TKL", "model" to "T-Echo", "class" to "tracker", "os" to "embedded", "contact" to "cfr34k-git@tkolb.de"),
			"APLG??" to mapOf("vendor" to "OE5BPA", "model" to "LoRa Gateway/Digipeater", "class" to "digi"),
			"APLIG?" to mapOf("vendor" to "TA2MUN/TA9OHC", "model" to "LightAPRS Tracker", "class" to "tracker"),
			"APLM??" to mapOf("vendor" to "WA0TQG", "class" to "software"),
			"APLO??" to mapOf("vendor" to "SQ9MDD", "model" to "LoRa KISS TNC/Tracker", "class" to "tracker"),
			"APLP0?" to mapOf("vendor" to "SQ9P", "model" to "fajne digi", "class" to "digi", "os" to "embedded", "contact" to "sq9p.peter@gmail.com"),
			"APLP1?" to mapOf("vendor" to "SQ9P", "model" to "LORA/FSK/AFSK fajny tracker", "class" to "tracker", "os" to "embedded", "contact" to "sq9p.peter@gmail.com"),
			"APLRG?" to mapOf("vendor" to "Ricardo, CD2RXU", "model" to "ESP32 LoRa iGate", "class" to "igate", "os" to "embedded", "contact" to "richonguzman@gmail.com"),
			"APLRT?" to mapOf("vendor" to "Ricardo, CD2RXU", "model" to "ESP32 LoRa Tracker", "class" to "tracker", "os" to "embedded", "contact" to "richonguzman@gmail.com"),
			"APLS??" to mapOf("vendor" to "SARIMESH", "model" to "SARIMESH", "class" to "software"),
			"APLT??" to mapOf("vendor" to "OE5BPA", "model" to "LoRa Tracker", "class" to "tracker"),
			"APLU0?" to mapOf("vendor" to "SP9UP", "model" to "ESP32/SX12xx LoRa iGate / Digi", "class" to "digi", "os" to "embedded", "contact" to "wajdzik.m@gmail.com"),
			"APLU1?" to mapOf("vendor" to "SP9UP", "model" to "ESP32/SX12xx LoRa Tracker", "class" to "tracker", "os" to "embedded", "contact" to "wajdzik.m@gmail.com"),
			"APMG??" to mapOf("vendor" to "Alex, AB0TJ", "model" to "PiCrumbs and MiniGate", "class" to "software"),
			"APMI01" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "WX3in1"),
			"APMI02" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "WXEth"),
			"APMI03" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "PLXDigi"),
			"APMI04" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "WX3in1 Mini"),
			"APMI05" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "PLXTracker"),
			"APMI06" to mapOf("vendor" to "Microsat", "os" to "embedded", "model" to "WX3in1 Plus 2.0"),
			"APMI??" to mapOf("vendor" to "Microsat", "os" to "embedded"),
			"APMON?" to mapOf("vendor" to "Amon Schumann, DL9AS", "model" to "APRS Balloon Tracker", "class" to "tracker", "os" to "embedded"),
			"APMPAD" to mapOf("vendor" to "DF1JSL", "model" to "Multi-Purpose APRS Daemon", "class" to "service", "contact" to "joerg.schultze.lutter@gmail.com", "features" to listOf("messaging")),
			"APMQ??" to mapOf("vendor" to "WB2OSZ", "model" to "Ham Radio of Things"),
			"APMT??" to mapOf("vendor" to "LZ1PPL", "model" to "Micro APRS Tracker", "class" to "tracker"),
			"APN102" to mapOf("vendor" to "Gregg Wonderly, W5GGW", "model" to "APRSNow", "class" to "app", "os" to "ipad"),
			"APN2??" to mapOf("vendor" to "VE4KLM", "model" to "NOSaprs for JNOS 2.0"),
			"APN3??" to mapOf("vendor" to "Kantronics", "model" to "KPC-3"),
			"APN9??" to mapOf("vendor" to "Kantronics", "model" to "KPC-9612"),
			"APNCM" to mapOf("vendor" to "Keith Kaiser, WA0TJT", "model" to "Net Control Manager", "class" to "software", "os" to "browser", "contact" to "wa0tjt@gmail.com"),
			"APND??" to mapOf("vendor" to "PE1MEW", "model" to "DIGI_NED"),
			"APNIC4" to mapOf("vendor" to "SQ5EKU", "model" to "BidaTrak", "class" to "tracker", "os" to "embedded"),
			"APNJS?" to mapOf("vendor" to "Julien Sansonnens, HB9HRD", "model" to "Web messaging service", "class" to "service", "contact" to "julien.owls@gmail.com", "features" to listOf("messaging")),
			"APNK01" to mapOf("vendor" to "Kenwood", "model" to "TM-D700", "class" to "rig", "features" to listOf("messaging")),
			"APNK80" to mapOf("vendor" to "Kantronics", "model" to "KAM"),
			"APNKMP" to mapOf("vendor" to "Kantronics", "model" to "KAM+"),
			"APNKMX" to mapOf("vendor" to "Kantronics", "model" to "KAM-XL"),
			"APNM??" to mapOf("vendor" to "MFJ", "model" to "TNC"),
			"APNP??" to mapOf("vendor" to "PacComm", "model" to "TNC"),
			"APNT??" to mapOf("vendor" to "SV2AGW", "model" to "TNT TNC as a digipeater", "class" to "digi"),
			"APNU??" to mapOf("vendor" to "IW3FQG", "model" to "UIdigi", "class" to "digi"),
			"APNV0??" to mapOf("vendor" to "SQ8L", "model" to "VP-Digi", "os" to "embedded"),
			"APNV1??" to mapOf("vendor" to "SQ8L", "model" to "VP-Node", "os" to "embedded"),
			"APNV??" to mapOf("vendor" to "SQ8L"),
			"APNW??" to mapOf("vendor" to "SQ3FYK", "model" to "WX3in1", "os" to "embedded"),
			"APNX??" to mapOf("vendor" to "K6DBG", "model" to "TNC-X"),
			"APOA??" to mapOf("vendor" to "OpenAPRS", "model" to "app", "class" to "app", "os" to "ios"),
			"APOCSG" to mapOf("vendor" to "N0AGI", "model" to "POCSAG"),
			"APOG7?" to mapOf("vendor" to "OpenGD77", "model" to "OpenGD77", "os" to "embedded", "contact" to "Roger VK3KYY/G4KYF"),
			"APOLU?" to mapOf("vendor" to "AMSAT-LU", "model" to "Oscar", "class" to "satellite"),
			"APOPYT" to mapOf("vendor" to "Mike, NA7Q", "model" to "NA7Q Messenger", "class" to "software", "contact" to "mike.ph4@gmail.com"),
			"APOSAT" to mapOf("vendor" to "Mike, NA7Q", "model" to "Open Source Satellite Gateway", "class" to "service", "contact" to "mike.ph4@gmail.com"),
			"APOSMS" to mapOf("vendor" to "Mike, NA7Q", "model" to "Open Source SMS Gateway", "class" to "service", "contact" to "mike.ph4@gmail.com", "features" to listOf("messaging")),
			"APOT??" to mapOf("vendor" to "Argent Data Systems", "model" to "OpenTracker", "class" to "tracker"),
			"APOVU?" to mapOf("vendor" to "K J Somaiya Institute", "model" to "BeliefSat"),
			"APOZ??" to mapOf("vendor" to "OZ1EKD, OZ7HVO", "model" to "KissOZ", "class" to "tracker"),
			"APP6??" to mapOf("model" to "APRSlib"),
			"APPCO?" to mapOf("vendor" to "RadCommSoft, LLC", "model" to "PicoAPRSTracker", "class" to "tracker", "os" to "embedded", "contact" to "ab4mw@radcommsoft.com"),
			"APPIC?" to mapOf("vendor" to "DB1NTO", "model" to "PicoAPRS", "class" to "tracker"),
			"APPM??" to mapOf("vendor" to "DL1MX", "model" to "rtl-sdr Python iGate", "class" to "software"),
			"APPRIS" to mapOf("vendor" to "DF1JSL", "model" to "Apprise APRS plugin", "class" to "service", "contact" to "joerg.schultze.lutter@gmail.com", "features" to listOf("messaging")),
			"APPT??" to mapOf("vendor" to "JF6LZE", "model" to "KetaiTracker", "class" to "tracker"),
			"APQTH?" to mapOf("vendor" to "Weston Bustraan, W8WJB", "model" to "QTH.app", "class" to "software", "os" to "macOS", "features" to listOf("messaging")),
			"APR2MF" to mapOf("vendor" to "Mike, DL2MF", "model" to "MF2wxAPRS Tinkerforge gateway", "class" to "wx", "os" to "Windows"),
			"APR8??" to mapOf("vendor" to "Bob Bruninga, WB4APR", "model" to "APRSdos", "class" to "software"),
			"APRARX" to mapOf("vendor" to "Open Source", "model" to "radiosonde_auto_rx", "class" to "software", "os" to "Linux/Unix"),
			"APRFG?" to mapOf("vendor" to "RF.Guru", "contact" to "info@rf.guru"),
			"APRFGB" to mapOf("vendor" to "RF.Guru", "model" to "APRS LoRa Pager", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGD" to mapOf("vendor" to "RF.Guru", "model" to "APRS Digipeater", "class" to "digi", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGH" to mapOf("vendor" to "RF.Guru", "model" to "Hotspot", "class" to "rig", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGI" to mapOf("vendor" to "RF.Guru", "model" to "LoRa APRS iGate", "class" to "igate", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGL" to mapOf("vendor" to "RF.Guru", "model" to "Lora APRS Digipeater", "class" to "digi", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGM" to mapOf("vendor" to "RF.Guru", "model" to "Mobile Radio", "class" to "rig", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGP" to mapOf("vendor" to "RF.Guru", "model" to "Portable Radio", "class" to "ht", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGR" to mapOf("vendor" to "RF.Guru", "model" to "Repeater", "class" to "rig", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGT" to mapOf("vendor" to "RF.Guru", "model" to "LoRa APRS Tracker", "class" to "tracker", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRFGW" to mapOf("vendor" to "RF.Guru", "model" to "LoRa APRS Weather Station", "class" to "wx", "os" to "embedded", "contact" to "info@rf.guru"),
			"APRG??" to mapOf("vendor" to "OH2GVE", "model" to "aprsg", "class" to "software", "os" to "Linux/Unix"),
			"APRHH?" to mapOf("vendor" to "Steven D. Bragg, KA9MVA", "model" to "HamHud", "class" to "tracker"),
			"APRNOW" to mapOf("vendor" to "Gregg Wonderly, W5GGW", "model" to "APRSNow", "class" to "app", "os" to "ipad"),
			"APRPR?" to mapOf("vendor" to "Robert DM4RW, Peter DL6MAA", "model" to "Teensy RPR TNC", "class" to "tracker", "os" to "embedded", "contact" to "dm4rw@skywaves.de"),
			"APRRDZ" to mapOf("model" to "rdzTTGOsonde", "vendor" to "DL9RDZ", "class" to "tracker"),
			"APRRF?" to mapOf("vendor" to "Jean-Francois Huet F1EVM", "model" to "Tracker for RRF", "class" to "tracker", "os" to "embedded", "contact" to "f1evm@f1evm.fr", "features" to listOf("messaging")),
			"APRRT?" to mapOf("vendor" to "RPC Electronics", "model" to "RTrak", "class" to "tracker"),
			"APRS" to mapOf("vendor" to "Unknown", "model" to "Unknown"),
			"APRX??" to mapOf("vendor" to "Kenneth W. Finnegan, W6KWF", "model" to "Aprx", "class" to "igate", "os" to "Linux/Unix"),
			"APS???" to mapOf("vendor" to "Brent Hildebrand, KH2Z", "model" to "APRS+SA", "class" to "software"),
			"APSAR" to mapOf("vendor" to "ZL4FOX", "model" to "SARTrack", "class" to "software", "os" to "Windows"),
			"APSC??" to mapOf("vendor" to "OH2MQK, OH7LZB", "model" to "aprsc", "class" to "software"),
			"APSF??" to mapOf("vendor" to "F5OPV, SFCP_LABS", "model" to "embedded APRS devices", "os" to "embedded"),
			"APSFLG" to mapOf("vendor" to "F5OPV, SFCP_LABS", "model" to "LoRa/APRS Gateway", "class" to "digi", "os" to "embedded"),
			"APSFRP" to mapOf("vendor" to "F5OPV, SFCP_LABS", "model" to "VHF/UHF Repeater", "os" to "embedded"),
			"APSFTL" to mapOf("vendor" to "F5OPV, SFCP_LABS", "model" to "LoRa/APRS Telemetry Reporter", "os" to "embedded"),
			"APSFWX" to mapOf("vendor" to "F5OPV, SFCP_LABS", "model" to "embedded Weather Station", "class" to "wx", "os" to "embedded"),
			"APSK63" to mapOf("vendor" to "Chris Moulding, G4HYG", "model" to "APRS Messenger", "class" to "software", "os" to "Windows"),
			"APSMS?" to mapOf("vendor" to "Paul Dufresne", "model" to "SMS gateway", "class" to "software"),
			"APSRF?" to mapOf("vendor" to "SoftRF", "model" to "Ham Edition", "class" to "tracker", "os" to "embedded"),
			"APSTM?" to mapOf("vendor" to "W7QO", "model" to "Balloon tracker", "class" to "tracker"),
			"APSTPO" to mapOf("vendor" to "N0AGI", "model" to "Satellite Tracking and Operations", "class" to "software"),
			"APT2??" to mapOf("vendor" to "Byonics", "model" to "TinyTrak2", "class" to "tracker"),
			"APT3??" to mapOf("vendor" to "Byonics", "model" to "TinyTrak3", "class" to "tracker"),
			"APT4??" to mapOf("vendor" to "Byonics", "model" to "TinyTrak4", "class" to "tracker"),
			"APTB??" to mapOf("vendor" to "BG5HHP", "model" to "TinyAPRS"),
			"APTCHE" to mapOf("vendor" to "PU3IKE", "model" to "TcheTracker, Tcheduino", "class" to "tracker"),
			"APTCMA" to mapOf("vendor" to "Cleber, PU1CMA", "model" to "CAPI Tracker", "class" to "tracker"),
			"APTEMP" to mapOf("vendor" to "KL7AF", "model" to "APRS-Tempest Weather Gateway", "class" to "wx", "os" to "Linux/Unix", "contact" to "kl7af@foghaven.net"),
			"APTKJ?" to mapOf("vendor" to "W9JAJ", "model" to "ATTiny APRS Tracker", "os" to "embedded"),
			"APTNG?" to mapOf("vendor" to "Filip YU1TTN", "model" to "Tango Tracker", "class" to "tracker"),
			"APTPN?" to mapOf("vendor" to "KN4ORB", "model" to "TARPN Packet Node Tracker", "class" to "tracker"),
			"APTR??" to mapOf("vendor" to "Motorola", "model" to "MotoTRBO"),
			"APTT?" to mapOf("vendor" to "Byonics", "model" to "TinyTrak", "class" to "tracker"),
			"APTW??" to mapOf("vendor" to "Byonics", "model" to "WXTrak", "class" to "wx"),
			"APU1??" to mapOf("vendor" to "Roger Barker, G4IDE", "model" to "UI-View16", "class" to "software", "os" to "Windows"),
			"APU2?" to mapOf("vendor" to "Roger Barker, G4IDE", "model" to "UI-View32", "class" to "software", "os" to "Windows"),
			"APUDR?" to mapOf("vendor" to "NW Digital Radio", "model" to "UDR"),
			"APVE??" to mapOf("vendor" to "unknown", "model" to "EchoLink"),
			"APVM??" to mapOf("vendor" to "Digital Radio China Club", "model" to "DRCC-DVM", "class" to "igate"),
			"APVR??" to mapOf("vendor" to "unknown", "model" to "IRLP"),
			"APW9??" to mapOf("vendor" to "Mile Strk, 9A9Y", "model" to "WX Katarina", "class" to "wx", "os" to "embedded", "features" to listOf("messaging")),
			"APWA??" to mapOf("vendor" to "KJ4ERJ", "model" to "APRSISCE", "class" to "software", "os" to "Android"),
			"APWEE?" to mapOf("vendor" to "Tom Keffer and Matthew Wall", "model" to "WeeWX Weather Software", "class" to "software", "os" to "Linux/Unix"),
			"APWM??" to mapOf("vendor" to "KJ4ERJ", "model" to "APRSISCE", "class" to "software", "os" to "Windows Mobile", "features" to listOf("messaging", "item-in-msg")),
			"APWW??" to mapOf("vendor" to "KJ4ERJ", "model" to "APRSIS32", "class" to "software", "os" to "Windows", "features" to listOf("messaging", "item-in-msg")),
			"APW???" to mapOf("vendor" to "Sproul Brothers", "model" to "WinAPRS", "class" to "software", "os" to "Windows"),
			"APX???" to mapOf("vendor" to "Open Source", "model" to "Xastir", "class" to "software", "os" to "Linux/Unix"),
			"APXR??" to mapOf("vendor" to "G8PZT", "model" to "Xrouter"),
			"APY01D" to mapOf("vendor" to "Yaesu", "model" to "FT1D", "class" to "ht"),
			"APY02D" to mapOf("vendor" to "Yaesu", "model" to "FT2D", "class" to "ht"),
			"APY05D" to mapOf("vendor" to "Yaesu", "model" to "FT5D", "class" to "ht"),
			"APY300" to mapOf("vendor" to "Yaesu", "model" to "FTM-300D", "class" to "rig"),
			"APY400" to mapOf("vendor" to "Yaesu", "model" to "FTM-400", "class" to "rig"),
			"APYS??" to mapOf("vendor" to "W2GMD", "model" to "Python APRS", "class" to "software"),
			"APZ18" to mapOf("vendor" to "IW3FQG", "model" to "UIdigi", "class" to "digi"),
			"APZ186" to mapOf("vendor" to "IW3FQG", "model" to "UIdigi", "class" to "digi"),
			"APZ19" to mapOf("vendor" to "IW3FQG", "model" to "UIdigi", "class" to "digi"),
			"APZ247" to mapOf("model" to "UPRS", "vendor" to "NR0Q"),
			"APZG??" to mapOf("vendor" to "OH2GVE", "model" to "aprsg", "class" to "software", "os" to "Linux/Unix"),
			"APZMAJ" to mapOf("vendor" to "M1MAJ", "model" to "DeLorme inReach Tracker"),
			"APZMDR" to mapOf("vendor" to "Open Source", "model" to "HaMDR", "class" to "tracker", "os" to "embedded"),
			"APZTKP" to mapOf("vendor" to "Nick Hanks, N0LP", "model" to "TrackPoint", "class" to "tracker", "os" to "embedded"),
			"APZWKR" to mapOf("vendor" to "GM1WKR", "model" to "NetSked", "class" to "software"),
			"AP???D" to mapOf("vendor" to "Painter Engineering", "model" to "uSmartDigi D-Gate", "class" to "dstar"),
			"AP???U" to mapOf("vendor" to "Painter Engineering", "model" to "uSmartDigi Digipeater", "class" to "digi"),
			"PSKAPR" to mapOf("vendor" to "Open Source", "model" to "PSKmail", "class" to "software")
		)
									
		// Kotlin equivalent of process_tocall
		fun processTocall(tocall: String): String? {
			println("Input: $tocall")

			// 1. Check for exact match in TOCALL_DATA
			if (TOCALL_DATA.containsKey(tocall)) {
				println("Exact match found.")
				// Cast the value to a Map and then get the "model" value as a String
				return (TOCALL_DATA[tocall] as? Map<String, Any>)?.get("model") as? String
			}

			// 2. Find the best match with wildcard ("?") in the key
			val bestMatchTocall = TOCALL_DATA.keys
				.filter { it.contains("?") && it.length == tocall.length && tocall.startsWith(it.dropLast(it.count { char -> char == '?' })) }
				.maxByOrNull { it.dropLast(it.count { char -> char == '?' }).length }

			return bestMatchTocall?.let { 
				// Cast the value to a Map and get the "model" value as a String
				(TOCALL_DATA[it] as? Map<String, Any>)?.get("model") as? String
			} ?: null // Return null if no match found, instead of returning tocall
		}


        // Function to check if the last 2 characters of the comment match anything in COMMENT_DATA
        fun micetocall(comment: String): String? {
            val lastTwoChars = comment.takeLast(2) // Get the last 2 characters of the comment
            return COMMENT_DATA[lastTwoChars]?.get("model")
        }
    }
}
